routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/rooms', 'HomeController@index')->name('home');

Route::resource('rooms', 'RoomController')->parameters(['room' => '[0-9]+']);

Route::resource('/rooms/{room}/reserveds', 'ReservedController')->parameters(['reserveds' => '[0-9]+'])->only(['index', 'show', 'store', 'destroy']);

app/Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    protected $fillable = ['address_id', 'label', 'size', 'description', 'price', 'bedrooms', 'housing_id', 'owner_id' ];

    public function reservations()
    {
        return $this->hasMany(Reserved::class);
    }

    public function equipment()
    {
        return $this->belongsToMany(Equipment::class, 'equipment_rooms');
    }

    public function housing()
    {
        return $this->belongsTo(HousingType::class);
    }

    public function address()
    {
        return $this->belongsTo(Address::class);
    }

    public function addEquipment(array $equipments)
    {
        return $this->equipment()->attach($equipments);
    }

    public function removeAllEquipments()
    {
        return $this->equipment()->detach();
    }

    public function hasEquipment(int $id)
    {
        return $this->equipment->contains($id);
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Equipment;
use App\Room;
use App\Address;
use Auth;
use App\Image;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\HousingType;
use App\Equipments;

class RoomController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
        $this->middleware('room.owner')->only(['update', 'edit', 'destroy']);
        $this->middleware('auth.advertiser')->only('create');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rooms = Room::all();
        return view('room.index', compact('rooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $equipments = Equipment::all();
        $housings = HousingType::all();
        return view('room.create', compact('equipments', 'housings'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fields = $request->validate([
            'label' => 'required|max:50',
            'description' => 'required',
            'country' => 'required',
            'city' => 'required',
            'bedrooms' => 'required|integer',
            'size' => 'required|integer',
            'price' => 'required|between:0,999.999.99',
            'housing_id' => 'required|integer',
            'equipments' => ''
        ]);
        $address = Address::create($fields);

        $fields['owner_id'] = Auth::user()->id;
        $fields['address_id'] = $address->id;

        $room = Room::create($fields);
        $room->addEquipment($fields['equipments']);

        return redirect(route('rooms.show', $room));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function show(Room $room)
    {
        $owner = User::find($room->owner_id);
        return view('room.show', compact('room', 'owner'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function edit(Room $room)
    {
        $equipments = Equipment::all();
        $housings = HousingType::all();
        return view('room.edit', compact('room', 'equipments', 'housings'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Room $room)
    {
        $fields = $request->validate([
            'label' => 'required|max:50',
            'description' => 'required',
            'bedrooms' => 'required|integer',
            'size' => 'required|integer',
            'price' => 'required|between:0,999.999.99',
            'housing_id' => 'required|integer',
            'equipments' => ''
        ]);

        $room->update($fields);
        if(!empty($request->equipments)){
            $room->removeAllEquipments();
            $room->addEquipment($fields['equipments']);
        }
        return redirect(route('rooms.show', $room));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function destroy(Room $room)
    {
        $room->delete();
        return redirect(route('rooms.index'));
    }
}

resources/views/room/create.blade.php
@extends('layouts.app')

@section('title', 'Create room')

@section('content')

@if (count($errors) > 0)
    <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
    </div>
@endif

<form action="{{route('rooms.store')}}" method="POST" enctype="multipart/form-data">
@csrf
    <h1> Create Room : </h1>
        <label>
            <span>Country : </span>
            <input type="text" name="country" value="{{old('country')}}">
        </label>
        <label>
            <span>City : </span>
            <input type="text" name="city" value="{{old('city')}}">
        </label>
        <label>
            <span>Name (Little description) : </span>
            <input type="text" name="label" value="{{old('label')}}">
        </label>
        <label>
            <span>Description : </span>
            <textarea type="text" name="description" placeholder="Discribe your room, insert link or other.">{{old('description')}}</textarea>
        </label>
        <label>
            <span>Number of bed : </span>
            <input type="text" name="bedrooms" placeholder="Number of bed." value="{{old('bedrooms')}}">
        </label>
        <label>
            <span>Size of your room : </span>
            <input type="text" name="size" placeholder="Size." value="{{old('size')}}">
        </label>
        <label>
            <span>Price : </span>
            <input type="text" name="price" placeholder="Price, for ONE night." value="{{old('price')}}">
        </label>
        <div class="select-checkbox">
            @foreach ($equipments as $equipment)
                <label>
                    <span>{{$equipment->label}}</span>
                    <input type="checkbox" name="equipments[]" value="{{$equipment->id}}">
                </label>
            @endforeach
        </div>
        <label>
            <select name="housing_id">
                <option value="0">Please, choose a house type : </option>
                @foreach ($housings as $housing)
                    <option value="{{$housing->id}}">{{$housing->label}}</option><br>
                @endforeach
            </select>
        </label>
        <label>
            <label>Choose your pictures (0-5) : </label>
            <input name="images[]" type="file" multiple>
        </label>
        <button type="submit" class="btn btn-outline-primary">Create now !</button>
    </form>
@endsection

resources/views/room/edit.blade.php
@extends('layouts.app')

@section('title', 'Update room')

@section('content')

@if (count($errors) > 0)
    <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
    </div>
@endif

<form action="{{route('rooms.update', $room)}}" method="POST" enctype="multipart/form-data">
@csrf
    <input type="hidden" name="_method" value="PUT">
    <h1> Update Room : </h1>
        <label>
            <span>Name (Little description) : </span>
            <input type="text" name="label" value="{{old('label') ?: $room->label}}">
        </label>
        <label>
            <span>Description : </span>
            <textarea type="text" name="description" placeholder="Discribe your room, insert link or other.">{{old('description') ?: $room->description}}</textarea>
        </label>
        <label>
            <span>Number of bed : </span>
            <input type="text" name="bedrooms" placeholder="Number of bed." value="{{old('bedrooms') ?: $room->bedrooms}}">
        </label>
        <label>
            <span>Size of your room : </span>
            <input type="text" name="size" placeholder="Size." value="{{old('size') ?: $room->size}}">
        </label>
        <label>
            <span>Price : </span>
            <input type="text" name="price" placeholder="Price, for ONE night." value="{{old('price') ?: $room->price}}">
        </label>
        <div class="select-checkbox">
            @foreach ($equipments as $equipment)
                <label>
                    <span>{{$equipment->label}}</span>
                    <input
                        type="checkbox"
                        value="{{$equipment->id}}"
                        name="equipments[]"
                        {{$room->hasEquipment($equipment->id) ? 'checked': ''}}
                    >
                </label>
            @endforeach
        </div>
        <label>
            <select name="housing_id">
                <option value="0">Please, choose a house type : </option>
                @foreach ($housings as $housing)
                    <option value="{{$housing->id}}" {{($room->housing->id == $housing->id) ? 'selected' : ''}}>{{$housing->label}}</option><br>
                @endforeach
            </select>
        </label>
        <button type="submit" class="btn btn-outline-primary">Update now !</button>
    </form>
@endsection

resources/views/room/index.blade.php
@extends('layouts.app')

@section('title', 'Home')

@section('content')
    @if( isset($rooms[0]) )
        @foreach($rooms as $room)
            <div>
                <b>Room name : </b><p>{{$room->label}}</p>
                <b>Little description : </b><p>{{str_limit($room->description, 250, '...')}}<a href="/rooms/{{$room->id}}">See rooms details.</a></p>
                <b>Price : </b><p>{{$room->price}}€ / nuit</p>
                <hr>
            </div>
        @endforeach
    @else
        <h2 class="text-center"><b>No rooms available.</b></h2>
    @endif
@endsection

resources/views/room/show.blade.php
@extends('layouts.app')

@section('title', $room->label)

@section('content')

@if (count($errors) > 0)
    <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
    </div>
@endif

    <div>
        <b>Room name : </b><p>{{str_replace('.', '', $room->label)}}, by {{$owner->name}}</p>
        <b>Little description : </b><p>{{$room->description}}</p>
        <b>Price : </b><p>{{$room->price}}€ / nuit</p>
        <b>Location : </b><p>{{$room->address->country}}, {{$room->address->city}}</p>
        <b>Housing type : </b><p>{{$room->housing->label}}, {{$room->bedrooms}} @if( $room->bedrooms > 1) lits @else lit @endif ({{$room->size}}m²)</p>
        @if(isset($room->equipment[0])) <b>Equipements : </b>@foreach($room->equipment as $equip)<p>{{$equip->label }}</p>@endforeach @else <b><p>No equipments available.</p></b>@endif
        @if(Auth::user())
            @if(Auth::user()->role_id == App\Role::Customer)
                <form action="{{route('reserveds.store', $room)}}" method="post">
                    @csrf
                    <div class="text-center"><p>Please choose a date : </p><input type="datetime-local"  name="start_time" value="<?php echo date('Y-m-d\TH:i') ?>"><input type="datetime-local" value="<?php echo date('Y-m-d\TH:i', strtotime( '+1 week' )) ?>" name="end_time"></div>
                    <p class="text-center"><b><button type="submit" class="btn btn-outline-primary w-100">Reserve now !</button></b></p>
                </form>
            @endif
        @else
            <h2 class="text-center"><b>Please <i><a href="{{route('register')}}">register</a></i> or <i><a href="{{route('login')}}">login</a></i> here to reserve this room.</b></h2>
        @endif
        @if( !empty(Auth::user()) && (Auth::user() && Auth::user()->id == $room->owner_id))
            <h2 class="text-center"><b>Click <i><a href="{{route('rooms.edit', $room)}}">here</a></i> to edit this room.</b></h2>
            <h2 class="text-center"><b>Click <button type="button" data-toggle="modal" data-target="#infos" class="btn btn-primary"><i>here</i></button> to delete this room.</b></h2>
            <div class="modal" id="infos">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Are your sure ?</h4>
                        </div>
                        <div class="modal-body">
                            If you click on "Delete", the room "{{$room->label}}" will be deleted.
                        </div>
                        <div class="modal-footer">
                            <form action="{{route('rooms.destroy', $room)}}" method="post">
                            @csrf
                            @method('DELETE')
                                <button class="btn btn-danger" type="submit"><em>Delete</em></button>
                            </form>
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><em>Close</em></button>
                        </div>
                    </div>
                </div>
            </div>
        @endif
        <hr>
    </div>
@endsection